// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error("환경 변수 DATABASE_URL을 설정해야 합니다.");
}
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
